# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - HitachiQA/*

pool:
  vmImage: 'windows-latest'

variables:
- name: BROWSER
  value: Chrome
- name: SourceDir
  value: '$(Build.SourcesDirectory)/HitachiQA'


steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/HitachiQA.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\HitachiQA.sln'
    restoreNugetPackages: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:BROWSER = "chrome"
      Write-Host "Current Browser Value is $env:BROWSER"

- task: VSTest@2
  displayName: 'Running a Smoke Test'
  continueOnError: true
  timeoutInMinutes: 10
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\HitachiQA.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'SmokeTest'

- task: CopyFiles@2
  displayName: 'Copy TestResults'
  inputs:
    SourceFolder: $(Agent.TempDirectory)/TestResults
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/TestResults'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Test Results Files'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/TestResults'
    ArtifactName: 'TestResults'
